services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
      - ./essnapshots:/usr/share/elasticsearch/snapshots
    environment:
      - discovery.type=single-node
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2G -Xmx2G"
      - xpack.reporting.csv.maxSizeBytes=10485760000
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=85%
      - cluster.routing.allocation.disk.watermark.high=90%
      - cluster.routing.allocation.disk.watermark.flood_stage=95%
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - http.max_content_length=5gb 
    restart: unless-stopped
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

networks:
  elastic-net:

volumes:
  esdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/esdata
  essnapshots:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/essnapshots
